src/AppBundle/Entity/Field.php
<?php

namespace AppBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * Field
 *
 * @ORM\Table(name="field")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\FieldRepository")
 */
class Field
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="reference", type="string", length=255, nullable=true)
     */
    private $reference;

    /**
     * @var string
     *
     * @ORM\Column(name="unit", type="string", length=32, nullable=true)
     */
    private $unit;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_title", type="boolean", nullable=false, options={"default":0})
     */
    private $is_title;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="modified_at", type="datetime")
     */
    private $modifiedAt;

    /**
     * @var string
     *
     * @ORM\Column(name="created_by", type="string", length=255)
     */
    private $createdBy;

    /**
     * @var string
     *
     * @ORM\Column(name="modified_by", type="string", length=255)
     */
    private $modifiedBy;
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Field
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set reference
     *
     * @param string $reference
     *
     * @return Field
     */
    public function setReference($reference)
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * Get reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Set unit
     *
     * @param string $unit
     *
     * @return Field
     */
    public function setUnit($unit)
    {
        $this->unit = $unit;

        return $this;
    }

    /**
     * Get unit
     *
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Set is_title
     *
     * @param string $is_title
     *
     * @return Field
     */
    public function setIsTitle($is_title)
    {
        $this->is_title = $is_title;

        return $this;
    }

    /**
     * Get is_title
     *
     * @return string
     */
    public function getIsTitle()
    {
        return $this->is_title;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Field
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set modifiedAt
     *
     * @param \DateTime $modifiedAt
     *
     * @return Field
     */
    public function setModifiedAt($modifiedAt)
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    /**
     * Get modifiedAt
     *
     * @return \DateTime
     */
    public function getModifiedAt()
    {
        return $this->modifiedAt;
    }

    /**
     * Set createdBy
     *
     * @param string $createdBy
     *
     * @return Field
     */
    public function setCreatedBy($createdBy)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set modifiedBy
     *
     * @param string $modifiedBy
     *
     * @return Field
     */
    public function setModifiedBy($modifiedBy)
    {
        $this->modifiedBy = $modifiedBy;

        return $this;
    }

    /**
     * Get modifiedBy
     *
     * @return string
     */
    public function getModifiedBy()
    {
        return $this->modifiedBy;
    }

}

src/AppBundle/Controller/OrderController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Company;
use AppBundle\Entity\Discount;
use AppBundle\Entity\Order;
use AppBundle\Entity\Detail;
use AppBundle\Entity\ResultFile;
use AppBundle\Entity\User;
use AppBundle\Service\FileUploader;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * Order controller.
 *
 * @Route("order")
 */
class OrderController extends Controller
{
    /**
     * Lists all order entities.
     *
     * @Route("/", name="order_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        return $this->render('order/index.html.twig');
    }

    /**
     * Lists all order entities.
     *
     * @Route("/doctor/{id}", name="order_index_doctor")
     * @Method("GET")
     * @param User $doctor
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexDoctorAction(User $doctor)
    {
        $em = $this->getDoctrine()->getManager();

        $orders = $em->getRepository('AppBundle:Order')->findBy(array('doctor' => $doctor->getId()), array('id' => 'DESC'));

        return $this->render('order/index.html.twig', array(
            'orders' => $orders,
        ));
    }

    /**
     * Creates a new order entity.
     *
     * @Route("/new", name="order_new")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        $order = new Order();
        $form = $this->createForm('AppBundle\Form\OrderType', $order, ['user' => $this->getUser()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $exams = $form->get('laboratory_1')->getData()->toArray();
            $exams = array_merge($form->get('laboratory_2')->getData()->toArray(), $exams);
            $exams = array_merge($form->get('xray')->getData()->toArray(), $exams);
            $exams = array_merge($form->get('echo')->getData()->toArray(), $exams);
            $exams = array_merge($form->get('contrasted')->getData()->toArray(), $exams);
            $exams = array_merge($form->get('mama')->getData()->toArray(), $exams);
            $exams = array_merge($form->get('scan')->getData()->toArray(), $exams);

            $orderDate = new \DateTime($form->get('created_at')->getData());

            $order->setCreatedAt($orderDate);

            $order->setUser($this->getUser());


            foreach ($exams as $exam){
                $detail = new Detail();
                $detail->setOrder($order);
                $detail->setExam($exam);
                $order->addDetail($detail);

                $em->persist($detail);
                $em->persist($order);
            }

            $em->persist($order);
            $em->flush();

            $order = new Order();
            $form = $this->createForm('AppBundle\Form\OrderType', $order, ['user' => $this->getUser()]);
            return $this->render('order/new.html.twig', array(
                'order' => $order,
                'form' => $form->createView(),
            ));
        }

        return $this->render('order/new.html.twig', array(
            'order' => $order,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a order entity.
     *
     * @Route("/{id}", name="order_show")
     * @Method("GET")
     * @param Order $order
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction(Order $order)
    {
        $deleteForm = $this->createDeleteForm($order);

        return $this->render('order/show.html.twig', array(
            'order' => $order,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Finds and displays a order entity.
     *
     * @Route("/detail/{id}", name="order_detail")
     * @Method({"GET", "POST"})
     * @param Order $order
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showDetailsAction(Order $order, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $resultFile = new ResultFile();
        $form = $this->createForm('AppBundle\Form\UploadType', $resultFile);
        $form->handleRequest($request);

        $results = $em->getRepository("AppBundle:Result")->findBy(["order" => $order->getId()]);
        $array = [];
        foreach ($results as $r) {
            $array[$r->getField()->getId()] = $r->getValue();
        }

        if ($form->isSubmitted() && $form->isValid()) {


            $fileSystem = new Filesystem();
            $fileSystem->exists($this->getParameter('results_dir'));
            if ($fileSystem->exists($this->getParameter('results_dir').'/'.$order->getId())) {
                $fileSystem->remove([$this->getParameter('results_dir').'/'.$order->getId()]);

                $deleteFile = $em->getRepository('AppBundle:ResultFile')->findOneBy(['order' => $order->getId()]);
                $em->remove($deleteFile);
                $em->flush();
            }

            $file = $resultFile->getFile();
            $fileUploader = new FileUploader($this->getParameter('results_dir').'/'.$order->getId());

            /** @var UploadedFile $file */
            $fileName = $fileUploader->upload($file);

            $resultFile->setFile($fileName);
            $resultFile->setOrder($order);
            $resultFile->setFilename($file->getClientOriginalName());

            $em->persist($resultFile);
            $em->flush();

            return $this->render('order/detail.html.twig', array(
                'resultFile' => $resultFile,
                'order' => $order,
                'results' => $array,
                'form' => $form->createView()
            ));
        }

        return $this->render('order/detail.html.twig', array(
            'resultFile' => $resultFile,
            'order' => $order,
            'results' => $array,
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/download/{id}", name="download_file")
     * @param Order $order
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function downloadAction(Order $order)
    {
        $em = $this->getDoctrine()->getManager();
        $downloadFile = $em->getRepository('AppBundle:ResultFile')->findOneBy(['order' => $order->getId()]);
        $pdfPath = $this->getParameter('results_dir').'/'.$order->getId().'/'.$downloadFile->getFile();

        return $this->file($pdfPath, $downloadFile->getFilename());
    }

    /**
     * Displays a form to edit an existing order entity.
     *
     * @Route("/{id}/edit", name="order_edit")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @param Order $order
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, Order $order)
    {
        $deleteForm = $this->createDeleteForm($order);

        // var_dump($editForm->get('created_at')->getData()->format('Y-m-d'));
        // $dateC = $order->getCreatedAt()->format('Y-m-d');
        // var_dump($dateC);
        // $orderDate = new \DateTime(($editForm->get('created_at')->getData())->format('Y-m-d'));
        // $order->setCreatedAt($dateC);
        $editForm = $this->createForm('AppBundle\Form\EditOrderType', $order, ['user' => $this->getUser()]);
        $editForm->handleRequest($request);

         // var_dump($editForm->get('created_at')->getData());

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('order_edit', array('id' => $order->getId()));
        }
        return $this->render('order/edit.html.twig', array(
            'order' => $order,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a order entity.
     *
     * @Route("/{id}", name="order_delete")
     * @Method("DELETE")
     * @param Request $request
     * @param Order $order
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, Order $order)
    {
        $form = $this->createDeleteForm($order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($order);
            $em->flush();
        }

        return $this->redirectToRoute('order_index');
    }

    /**
     * Creates a form to delete a order entity.
     *
     * @param Order $order The order entity
     *
     * @return \Symfony\Component\Form\FormInterface
     */
    private function createDeleteForm(Order $order)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('order_delete', array('id' => $order->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }

    /**
     * @Route("/detail/preview/{id}", name="order_preview")
     * @Method("GET")
     * @param Order $order
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function previewAction(Order $order)
    {
        $data['patient'] = $order->getPatient()->getName();
        $data['doctor'] = $order->getDoctor()->getName();

        foreach($order->getDetails() as $detail){

src/AppBundle/Resources/views/Order/results.html.twig
{% extends "::base.html.twig" %}

{% block title %}Resultados{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ asset('bundles/mdbootstrap/css/addons/datatables.css') }}">
{% endblock %}

{% block body %}
    <button id="imprimir" class="btn btn-primary">Imprimir</button>
        <div class="row">
            <div class="col-md-6">
                <strong>Paciente: </strong><div id="paciente-nombre">{{ data.patient }}</div>
            </div>
            <div class="col-md-offset-3 col-md-3">
                <strong>Fecha: </strong><div id="reporte-fecha">{{ "now" | date("d/m/Y") }}</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <strong>Doctor: </strong><div id="reporte-doctor">{{ data.doctor }}</div>
            </div>
            <div class="col-md-offset-3 col-md-3">
                <strong>Edad: </strong><div id="paciente-edad">{{ data.age}} años</div>
            </div>
        </div>
        <br>
        <br>
    <div id="print-section">
        <div class="row">
            <div class="text-center">
                <input type="hidden" id="pagenumber" value="{{ data.exams|length }}">
                {%set idarr = 0%}
                {%set keysplit = 0%}
                {%set flaganti = 0%}
                {% for key, exam in data.exams %}

                    {%set keysplit = key|split(',')%}
                    <h4 id="titexam{{idarr}}" style="left: 50%;">{{ keysplit[0] }}</h4>

                    {% if keysplit[1] == 75 %}
                        <table id="tabexam{{idarr}}" class="table table-bordered table-condensed" style="font-size:12px; border: none !important;">
                            <thead>
                            <tr>
                                <td class="col-md-4"></td>
                                <td class="col-md-4"></td>
                                <td class="col-md-4"></td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for result in exam %}
                                {% if not result.field.isTitle %}
                                    <tr style="lineWidht: 0 !important;">
                                        <td style="lineWidht: 0 !important;">{{ result.field.name == '-' ? '' : result.field.name }}</td>
                                        <td style="border: none !important;">{{ result.value }}</td>
                                        <td style="border: none !important;">{{ result.field.reference == '-' ? '' : result.field.reference|nl2br }} {{ result.field.unit == '-' ? '' : result.field.unit }}</td>
                                    </tr>
                                {% else %}
                                    <tr id="sub" class="subtt">
                                        <td colspan="2" style="font-size:10px;" id="subtitulo" class="sbtt"><b>{{ result.field.name }}</b></td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                                <tr><td></td><td>S = SENSIBLE<br>M = MODERADAMENTE RESISTENTE<br>R = RESISTENTE</td><td></td></tr>
                            </tbody>
                        </table>
                    {% else %}
                        <table id="tabexam{{idarr}}" class="table table-bordered table-condensed" style="font-size:12px; border: none !important;">
                            <thead>
                            <tr>
                                <td class="col-md-4"></td>
                                <td class="col-md-4">Resultado</td>
                                <td class="col-md-4">Referencia</td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for result in exam %}
                                {% if not result.field.isTitle %}
                                    <tr style="lineWidht: 0 !important;">
                                        <td style="lineWidht: 0 !important;">{{ result.field.name == '-' ? '' : result.field.name }}</td>
                                        <td style="border: none !important;">{{ result.value }} {{ result.field.unit == '-' ? '' : result.field.unit }}</td>
                                        <td style="border: none !important;">{{ result.field.reference == '-' ? '' : result.field.reference|nl2br }} {{ result.field.unit == '-' ? '' : result.field.unit }}</td>
                                    </tr>
                                {% else %}
                                    <tr id="sub" class="subtt">
                                        <td colspan="2" style="font-size:10px;" id="subtitulo" class="sbtt"><b>{{ result.field.name }}</b></td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                    {% set idarr = idarr + 1  %}
                {% endfor %}
            </div>
        </div>
    </div>
    <p class="text-right" style="margin-top: 100px">
        QFB. JUDIT RIOS LARA <br>
        CED. 4346280
    </p>
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="{{ asset('bundles/mdbootstrap/js/mdb.js') }}"></script>
    <script src="{{ asset('bundles/mdbootstrap/js/popper.min.js') }}"></script>
    <script src="{{ asset('bundles/mdbootstrap/js/addons/datatables.js') }}"></script>

    <script src="{{ asset('bundles/jspdf/dist/jspdf.min.js') }}"></script>
    <script src="{{ asset('bundles/jspdf/plugins/autotable.min.js') }}"></script>
    <script src="{{ asset('bundles/jspdf/plugins/from_html.js') }}"></script>
    <script src="{{ asset('bundles/jspdf/plugins/split_text_to_size.js') }}"></script>
    <script src="{{ asset('bundles/jspdf/plugins/standard_fonts_metrics.js') }}"></script>

    <script>

        $('#imprimir').click(function () {
            let doc = new jsPDF('p', 'pt', 'letter');
            let elem = document.getElementById('main');

            let pnombre = document.getElementById('paciente-nombre').innerHTML;
            let rfecha = document.getElementById('reporte-fecha').innerHTML;
            let rdoctor = document.getElementById('reporte-doctor').innerHTML;
            let pedad = document.getElementById('paciente-edad').innerHTML;

            let paginas = document.getElementById('pagenumber').value;

            doc.setFontSize(10);
            if(paginas > 1){
                let cont;
                for(cont = 0; cont < paginas; cont ++){
                    if(pnombre){
                        doc.text(150,65,"Paciente: "+pnombre);
                    }
                    if(rfecha){
                        doc.text(450,80,"Fecha: "+rfecha);
                    }
                    if(rdoctor){
                        doc.text(150,80,rdoctor);
                    }
                    if(pedad){
                        doc.text(450,65,"Edad: "+pedad);
                    }

                    let titstring =  document.getElementById('titexam'+cont).innerHTML;
                    xOffset = (doc.internal.pageSize.width / 2) - (doc.getStringUnitWidth(titstring) * 12 / 2); 

                    doc.fromHTML($('#titexam'+cont).get(0), xOffset, 110, {
                                lineWidht: 0,
                        styles: {
                                fontSize: 2,
                            }
                    });

                    var res = doc.autoTableHtmlToJson(document.getElementById("tabexam"+cont));
                    doc.autoTable(res.columns, res.data, 
                    {
                        columnStyles: {
                            0: {columnWidth: 190},
                            1: {columnWidth: 200},
                            2: {columnWidth: 200}
                        },
                        createdCell: function(cell, data) { 

                            data.row.height = 20;
                                cell.styles.fontSize = 9; 

                            if (data.row.raw[0].id === "subtitulo") { 
                                cell.styles.fontStyle = 'bold'; 
                                cell.styles.fontSize = 10; 
                                data.row.cells[0].width = 400;
                                data.row.cells[0].y = 400;

                                data.row.y = 400;
                            } 

                        },
                        margin: {top: 170},
                        theme: 'plain',
                        rowHeight: 0,
                        styles: {
                            overflow: 'linebreak'
                        }

                    });

                    doc.text(380,722,'QFB. JUDIT RIOS LARA');
                    doc.text(380,733,'CED. 4346280');

                    if((cont + 1) != paginas){
                        doc.addPage();
                    }
                }
            }else{
            
                if(pnombre){
                    doc.text(150,65,"Paciente: "+pnombre);
                }
                if(rfecha){
                    doc.text(450,80,"Fecha: "+rfecha);
                }
                if(rdoctor){
                    doc.text(150,80,rdoctor);
                }
                if(pedad){
                    doc.text(450,65,"Edad: "+pedad);
                }

                let titstring =  document.getElementById('titexam0').innerHTML;
                xOffset = (doc.internal.pageSize.width / 2) - (doc.getStringUnitWidth(titstring) * 12 / 2);
                doc.fromHTML($('#titexam0').get(0), xOffset, 110, {
                    lineWidht: 0,
                    styles: {
                        fontSize: 2,
                    }
                });

                var res = doc.autoTableHtmlToJson(document.getElementById("tabexam0"));
                doc.autoTable(res.columns, res.data, 
                    {
                        columnStyles: {
                           0: {columnWidth: 190},
                           1: {columnWidth: 200},
                           2: {columnWidth: 200}
                        },
                        createdCell: function(cell, data) { 

                            //console.log("height: " + data.table.height);

                            //console.log(cell.text);
                            console.log(data.row);
                            //console.log(data.row.raw[0].id);
                            //console.log(data.column.dataKey);

                            data.row.height = 20;
                                cell.styles.fontSize = 9; 

                            if (data.row.raw[0].id === "subtitulo") { 
                                cell.styles.fontStyle = 'bold'; 
                                cell.styles.fontSize = 10; 
                                //data.row.cells[0].styles.cellPadding = 3;
                                //data.row.cells[0].styles.columnWidth = 600;
                                //data.row.cells[0].styles.colSpan = 2;
                                data.row.cells[0].width = 400;
                                data.row.cells[0].y = 400;

                                //doc.autoTableText(cell.text + '', data.settings.margin.left + data.table.width / 2, data.row.y + data.row.height / 2, {
                                  //  halign: 'center',
                                    //valign: 'middle'
                                //});

                                data.row.y = 400;
                            } 

                        },

                        margin: {top: 170},
                        theme: 'plain',
                        //theme: 'grid',
                        rowHeight: 0,
                        
                        styles: {
                            overflow: 'linebreak'
                          }

                    });


                doc.text(380,722,'QFB. JUDIT RIOS LARA');
                doc.text(380,733,'CED. 4346280');
            }

            doc.save("resultados.pdf");
        });



    </script>
{% endblock %}